### ISSUE TITLE
Missing member data for presence channel

### ISSUE THREAD

**Issue by meijdenmedia** [tlaverdure/laravel-echo-server#278] opened 2018-03-13 16:06 UTC
I'm trying to join a presence channel but can't get it to work. 
Currently using laravel-echo-server 1.3.6

This is my javascript code:
```
window.Echo.join('page.view.1')
                .here(function(users) {
                    console.log(users);
                })
                .joining(function(user) {
                    console.log(user);
                })
                .leaving(function(user) {
                    console.log(user.name);
                });
```

And the laravel authorisation:
```
Broadcast::channel('page.view.{route}', function (User $user, $route) {
    if(true) {
        \Log::info('Incoming broadcast auth ', ['id' => $user->id, 'name' => $user->profile->display_name]);
        
        return ['id' => $user->id, 'name' => $user->profile->display_name];
    }
});
```

In my laravel logs I can see the incoming broadcast auth with correct data.
```
[2018-03-13 17:04:22] local.INFO: Incoming broadcast auth  {"id":1234,"name":"John Doe"}
```

In the laravel-echo-server logs I got the following data:
```
[16:04:22] - t_4kcuRbspEYEaP6AAAB authenticated for: presence-page.view.1
Unable to join channel. Member data for presence channel missing
[16:04:22] - t_4kcuRbspEYEaP6AAAB joined channel: presence-page.view.1
```

Any idea what i'm doing wrong?

**Comment by zen4dev** [comment] 2018-03-21 05:46
I have same issue, private channals work perfectly.
Any one to help us?

**Comment by meijdenmedia** [comment] 2018-03-28 11:45
@tlaverdure can you maybe explain why this isn't working? Are we doing something wrong?

**Comment by skatetdieu** [comment] 2018-04-17 18:38
Are you guys hooking into the Laravel User Auth system? It might be that if you're using a custom way to sign in users. Check out this answer to that same issue I ran into:

https://stackoverflow.com/a/45782726/5464316

**Comment by tthdvd** [comment] 2018-04-26 09:04
@skatetdieu we implement the same working logic, but always getting the error.

**Comment by skatetdieu** [comment] 2018-04-26 15:45
@tthdvd do you have the laravel debug bar on your system? If so, is it showing you logged in under the Auth tab? 

Also, are the routes setup on your channels.php file to make sure it returns the user?

**Comment by tthdvd** [comment] 2018-04-27 08:58
@skatetdieu we rolled back to 1.3.2, but have the problem. 

When we want to join a presence channel we got the following error:
`[10:43:17] - SdRN-9ZclBilDi9BAAAE authenticated for: presence-messages-channel-4
[object Object] undefined presence-messages-channel-4
[10:43:17] - SdRN-9ZclBilDi9BAAAE joined channel: presence-messages-channel-4
(node:27206) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot set property 'socketId' of undefined`

It said, The use joined, but the client side 'join' method does not triggered. 

Well, I'm returning with the $user object now, the error same. 

Now I updated to 1.3.6 and the error is the following:
`[10:48:20] - Qi2fYgNvqoe_SSvAAAAK authenticated for: presence-messages-channel-4
Unable to join channel. Member data for presence channel missing
[10:48:20] - Qi2fYgNvqoe_SSvAAAAK joined channel: presence-messages-channel-4`

I guess, that would be the reason, we are getting this:
https://github.com/tlaverdure/laravel-echo-server/issues/202#issuecomment-342943425

We are returning with this: 
return ['id' => $user->id, 'name' => $user->profile->display_name];
because of the official laravel doc:
https://laravel.com/docs/5.4/broadcasting#presence-channels

You can see on the console log: the authentication is correct.

**Comment by skatetdieu** [comment] 2018-04-27 13:02
@tthdvd basically what it means is that your `$user` object isn't actually returning a record from the database. Not sure how you're handling your login and authentication for users, but that seems to be the issue. 

If you use the Laravel `Auth` facade class and run `Auth:user()` does it return the logged in user?

**Comment by tthdvd** [comment] 2018-04-27 13:32
@tlaverdure 
It is returning with the user data:
`[2018-04-27 15:25:45] local.INFO: {"id":2,"first_name":"Name1","last_name":"nam1","email":"tester1@test.hu","active":1,"created_at":"2018-03-26 22:01:25","updated_at":"2018-03-27 15:37:28","last_log":null,"deleted_at":null}  `

I'm using the laravel passport for the authentication (the frontend are written in ReactJs). I think it shouldn't be a problem. 

In my BroadcastServiceProvider:
```
public function boot()
   {
        Broadcast::routes(['middleware' => 'auth:api']);`

        require base_path('routes/channels.php');
    }
```
It's working for the basic private channels.

**Comment by skatetdieu** [comment] 2018-04-27 18:38
Hmm, I think the issue is that Laravel has two auth methods. It has a web authentication, which is what the echo server uses, and it has the API authentication, which is what Laravel Passport is for. 

So that might the issue. You're logged in via the API authentication, but not the web authentication. This is what it looks like in my system's debug bar:

![image](https://user-images.githubusercontent.com/1899636/39379078-317fdbb2-4a28-11e8-979a-4e170ed44553.png)

I don't have Laravel Passport going for API routes, so mine shows as a guest. But on the web authentication is shows my info. 

You setup the middleware to look at the api authentication, but the underlying code is still trying to get the user from the web authentication.

Unfortunately, you gotta setup web authentication for Laravel to successfully return the logged in user.

**Comment by meijdenmedia** [comment] 2018-05-07 13:48
@skatetdieu I'm using the web authentication and my user data is available via `\Auth::user();`
In my logs I can see `Incoming broadcast auth` with the correct user information.

**Comment by skatetdieu** [comment] 2018-05-07 19:19
@meijdenmedia And you do have your broadcast channels setup in channels.php in the routes folder returning the `$user` object?

**Comment by meijdenmedia** [comment] 2018-05-08 07:35
channels.php

```Broadcast::channel('page.view.{route}', function (\App\Domain\Models\User\User $user, $route) {
    \Log::info("IN");
    if($user->hasGroup(\App\Domain\Models\User\Group::SLUG_ADMINS)) {
    
        \Log::info('Incoming broadcast auth ', ['id' => $user->id, 'name' => $user->profile->display_name]);
        
        return ['id' => $user->id, 'name' => $user->profile->display_name];
    }
});
```

Both `return ['id' => $user->id, 'name' => $user->profile->display_name];` and `return $user->id;` give the missing data error. Data is correctly written to the Laravel logs (Incoming broadcast auth ..)

**Comment by skatetdieu** [comment] 2018-05-11 15:36
@meijdenmedia hmm, well then I honestly don't know what the issue is if the broadcast channel is being hit and returns the data properly.

**Comment by meijdenmedia** [comment] 2018-05-29 15:11
Yeah, it's really strange 😞

**Comment by wilsonwg** [comment] 2018-06-20 03:44
I had the same issue. Then I realized that I forgot to set the env variable. I edited laravel .env and set broadcast driver to redis. 

> BROADCAST_DRIVER=redis

Then the problem is no more.

**Comment by skatetdieu** [comment] 2018-06-20 13:35
@wilsonwg that's so true! Redis has to broadcast the $user object for the Echo server to catch it and join the channel!

**Comment by mitulmarsonia** [comment] 2018-09-20 10:36
I have fixed it just add prefix **presence-** 
My channel name is **current_login_user** now i'm going to call api with channel name **presence-current_login_user** just review below api url example.

http://localhost:6001/apps/APP_ID/channels/presence-current_login_user/users?auth_key=15a30727415f1ebb66d4a4c72f02e97b

**Comment by tlaverdure** [comment] 2018-11-30 17:34
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.

**Closed by tlaverdure** 2018-11-30 17:34 UTC

**Comment by infostreams** [comment] 2019-09-24 10:50
Another potential reason for this error is that you have setup your channel definitions incorrectly.

In routes/channels.php (laravel 5.8), you should return an array with 'id' field that contains the user id. If you don't do that you will get this error.

So make sure it looks something like this

```php
Broadcast::channel('chat.{chat}', function($user, $chat) { 
    if ($user->can('send', $chat)) {
        return ['id' => $user->id];
    }
    return false;
});
```

**Comment by pedrosancao** [comment] 2020-01-27 13:26
Thanks everybody for the provided info, that helped me to solve the same issue.
Also I found that the below code works (Laravel 5.8.36 & Laravel Echo Server 1.6.0)

```php
Broadcast::channel('sample-channel', function ($user) {
    return 1; // just cast to bool to int
});
```

**Comment by DorelBesliu** [comment] 2020-02-09 18:12
> I had the same issue. Then I realized that I forgot to set the env variable. I edited laravel .env and set broadcast driver to redis.
> 
> > BROADCAST_DRIVER=redis
> 
> Then the problem is no more.

Thank you very much !!!
