### ISSUE TITLE
/etc/hosts loopback entry causes refused connections.

### ISSUE THREAD

**Issue by trip-somers** [tlaverdure/laravel-echo-server#88] opened 2016-12-19 19:48 UTC
I've encountered a weird issue on a dev server. It's similar to several other issues (most similar to #72)  I've seen posted here, but seems to me to be unique and separate.

I was able to fully set up and start a Laravel Echo Server instance with my host set to "unique.domain.dev" (placeholder for actual domain that definitely doesn't collide with a Google-owned *.dev domain), but a ```nestat -l``` revealed that the server was only listening to requests made to "127.0.0.1".

The effect was that all external requests to "http://unique.domain.dev:6001" were refused connections, but internal connections originating from the dev server itself were fine.

After digging through tons of StackOverflow questions and answers plus the issues here, we decided to try just using the dev server's IP address. It worked, but as a solution it wouldn't be practical since we'd wind up with multiple dev instances accessing the same Laravel Echo Server instance, which would obviously be something between unpredictable and disastrous.

We thought pretty hard about why the IP worked and why the domain didn't. We looked at the hosts file on the dev server, and -- taking a shot in the dark -- we swapped out the "127.0.0.1 unique.domain.dev" entry for "[Dev Server's Network IP] unique.domain.dev".

Sure enough, ```netstat -l``` now shows that it's listening on the correct domain, and I'm able to connect as needed.

My issue/question: Why did a hosts file entry of "127.0.0.1 unique.domain.dev" effectively disable outside connections to the Laravel Echo Server? Alternatively, why did a hosts file entry of "[Dev Server's Network IP] unique.domain.dev" work?

**Comment by jonnywilliamson** [comment] 2016-12-20 23:24
Its a very long post (sorry) but I think this describes what you're talking about?

https://github.com/tlaverdure/laravel-echo-server/issues/33

It only started in the last few updates.

**Comment by trip-somers** [comment] 2016-12-20 23:41
That's part of the problem, sure, but it doesn't really get into explaining why a hosts file entry fixes the server setup. I meant to reference that issue, but I couldn't find it when I wrote my post (figured I had read that somewhere in a Node server project).

**Comment by jonnywilliamson** [comment] 2016-12-22 12:48
Here's an interesting thread.

https://github.com/nodejs/node-v0.x-archive/issues/9195

**Comment by trip-somers** [comment] 2016-12-22 18:55
Appreciate the extra digging, but that all seems to be IPv4 vs IPv6 stuff.

For clarification:

When my hosts entry was "127.0.0.1 unique.domain.dev", netstat showed a listener for: "127.0.0.1:6001".
When my hosts entry was "[Dev Server's Network IP] unique.domain.dev", netstat showed a listener for: "unique.domain.dev:6001".

If the explanation for that is somewhere in that thread, I couldn't parse it out. Did you see something that helped shed light on that?

**Comment by jonnywilliamson** [comment] 2016-12-22 21:48
I'm not 100% convinced that netstat is showing you the right info.

I think the netstat -l command is defaulting to show you domain names when it can (hence not able to how one when 127.0.0.1 is use).

Try this instead. I assume your port is 6001.


=======
1) Set your hosts file back to `127.0.0.1 unique.domain.dev`

2) Set your host in the laravel-echo-server config file to `unique.domain.dev`

3) Start the server. In another window (use tmux etc / new shell) type: `sudo netstat -tulnp | grep 6001`


My guess is that you'll see the echo server bound to 127.0.0.1

4) Now, change your hosts file to `<dev ip address> unique.domain.dev`

5) Restart the echo server

6) Rerun `sudo netstat -tulnp | grep 6001`
======

Can you post a screenshot now?

My bet is that you'll see an IP address and not a domain.


If thats the case, then it seems its exactly the same as #33

**Comment by trip-somers** [comment] 2016-12-23 05:19
I literally just started a 12-day vacation this afternoon, so I'll have to come back to this when I feel like touching my work laptop. Saving the email alert as new so that I remember to check back. I will let you know.

**Comment by trip-somers** [comment] 2017-01-04 05:37
@jonnywilliamson, I will be looking at this again tomorrow and will post an update.

**Comment by trip-somers** [comment] 2017-01-05 17:30
With hosts entry set to 127.0.0.1:

```
tcp        0      0 127.0.0.1:6001          0.0.0.0:*               LISTEN      1924/laravel-echo-s
```

With hosts entry set to [local network IP]:

```
tcp        0      0 [local network IP]:6001         0.0.0.0:*               LISTEN      2824/laravel-echo-s
```

It looks like you are correct, but here's what else I can see just by running ```netstat -l```. This line appears when the hosts entry is set to the local network IP:

```
tcp        0      0 [unique.domain.dev (truncated)]:x11-1 *:*                     LISTEN
```

The "same" line when the IP is set to 127.0.0.1:

```
tcp        0      0 localhost:x11-1         *:*                     LISTEN
```

This is the difference I was referring to with my initial remarks, so I think we're both right? Looking forward to your feedback/response.

**Comment by jonnywilliamson** [comment] 2017-01-05 22:43
Ok it's been a while since I've been looking at this and I need a short, sharp refresher. Also this should hopefully help anyone else just stumbling on this issue to catch up.

1 - We are testing how binding `echo server` to different ip address OR domain names causes different outcomes.
2 - Sometimes the echo script binds to a local adapter sometimes the "All-adapter" interface.
3 - Is this something that is a bug or a by design.

[Firstly, just a quick recap on adapters](http://stackoverflow.com/a/20778887/659786):

> "localhost" is normally the hostname for the 127.0.0.1 IP address. It's usually set in /etc/hosts (or the Windows equivalent named "hosts" somewhere under %WINDIR%). You can use it just like any other hostname - try "ping localhost" to see how it resolves to 127.0.0.1.
> 
> 0.0.0.0 has a couple of different meanings, but in this context, when a server is told to listen on 0.0.0.0 that means "listen on every available network interface". The loopback adapter with IP address 127.0.0.1 from the perspective of the server process looks just like any other network adapter on the machine, so a server told to listen on 0.0.0.0 will accept connections on that interface too.
> 


OK, finally to see what port and adapter is being used by `echo server` we were using 2 different commands:

You were using `sudo netstat -l`

I suggested `sudo netstat -tulnp`  (optionally add `| grep 6001` to find the line easier)

That will output a line that has the following columns
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN      1225/mysqld
```

Here's what each of the options are for netstat
```
-t tcp
-u udp
-l Show only listening sockets. (These are omitted by default.)
-n Show numerical addresses instead of trying to determine symbolic host, port or user names.
-p Show the PID and name of the program to which each socket belongs.
```

This is why when you look at your last 2 lines you posted above you see the `:x11-1` in there. Netstat is trying to use the port number to "guess" what service is running...but it uses a list to do this, and in our case port 6001 is assigned to X11 server. (http://www.penguintutor.com/linux/network-services-ports)

Of course it isn't running that at all! Using the above command options shows EXACTLY the port/process/IP(adapter) that is being used. There's no guesswork involved.

Anyway, back to the issue.

I'm probably really thick, but I'm still not able to follow what "discrepancy" you say there is? (I'm going to make your local dev sever ip address 192.168.1.1 because it hurts my brain trying to turn the words [local network IP] into a number)

- When you set your hosts file to set `example.dev` to point to `127.0.0.1` you got a response that showed that `echo server` attached to the local host adapter (127.0.0.1:6001) - So nothing outside of the server can connect to it.

- When you set your hosts file to set `example.dev` to point to `192.168.1.1` you got a response that showed that `echo server` attached to the host adapter (192.168.1.1:6001) - so this time (assuming 192.168.1.1 is contactable from outside your sever/network) anyone connecting to that will be successful.


Where the REAL difference is how this has changed from old versions (pre v1.0) and today's one.

In the past, even if your domain name pointed to localhost or `127.0.0.1` the echo server would bind to the `0.0.0.0` adapter and so you would be able to connect to it from inside or outside your sever.

Now, if your domain name points to localhost or `127.0.0.1` the echo server only binds to the localhost/127.0.0.1 adpater and so connection is limited strictly to connections from inside the server.

Is this by design? Perhaps? But that was the initial question I had - but it hasn't been answered yet (because it's complicated!)

I still think, you've just been confirming the issue, but perhaps have arrived at the same problem from a different path.

**Comment by trip-somers** [comment] 2017-01-06 00:01
My primary issue is that I followed all instructions for setting up Laravel Echo Server to work on a locally hosted domain, but when I tried to connect to that domain, all of my connections were refused. This is the case when the hosts entry pointed the domain to 127.0.0.1 and established a listener on the "localhost" pseduo-domain.

When I updated the hosts entry to point the domain to the local network IP, my connections all worked.

Literally the only change I made was the hosts entry. I made no changes to the Laravel Echo Server configuration; it was always supposed to be working on the domain... hence my confusion over why a hosts entry changes the domain on which my listener is active.

**Comment by trip-somers** [comment] 2017-01-06 00:24
That's the part I'm having trouble with. My Echo server is set up to *supposedly* listen to unique.domain.dev, but if I have a 127.0.0.1 hosts entry for that domain, I can not connect to it through that domain, only through 'localhost' which won't work in my browser.

As I understand it, from your explanation, it's because the server is creating a local adapter. I just don't understand why a hosts entry is causing that to happen.

**Comment by trip-somers** [comment] 2017-01-06 00:27
I guess we are asking the same question.

**Comment by stoneworld** [comment] 2017-01-15 06:18
same question

**Comment by perezale** [comment] 2017-03-14 22:26
Hi! I've absolutely no idea about what's going on with my solution, but its working so far. By following this comment idea:

> Actually in older versions of the echo-server script, if your domain pointed to local host, the script would attach to :::6001 ! Which I think is the same as 0.0.0.0:6001!

what I did was to try to point my domain expecting to get the echo server to listen on all adapters, that would be :::6001 in 'netstat'

so, i tryed this mapping at /etc/hosts:
`:: domain.dev`

and this is what i've got 😀  Now echo server listens on all-adapters!
`tcp6       0      0 :::6001                 :::*                    LISTEN      24734/laravel-echo-`

Note: echo server host is set to domain.dev

**Comment by trip-somers** [comment] 2017-03-16 02:05
That's very interesting. I wonder if that works on all systems or causes any kind of weird side effects.

**Comment by perezale** [comment] 2017-03-16 03:26
@trip-somers I believe it should, as the main idea of using :: came out of pre-configured system settings (at homestead hosts file).
And referring to the original question about whether it was a design decision or a bug, i think its not a bug. If loopback address stays between local boundaries, a local mapping to local interfaces should have the same behaviour.

Therefore, any explicit need to "open" listening ports must be done in such explicits ways. 

My doubt is if it is correct to have something dependent on hosts file.

**Comment by tlaverdure** [comment] 2018-11-30 17:02
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.

**Closed by tlaverdure** 2018-11-30 17:02 UTC
